default:
	@echo "There is no default command."

copy:
	cp ~/.bashrc ./bashrc
	cp ~/.bash_aliases ./bash_aliases
	cp ~/.bash_exports ./bash_exports

clean:
	rm -f bash*

restore:
	cp bashrc ~/.bashrc
	cp bash_aliases ~/.bash_aliases
	cp bash_exports ~/.bash_exports
